version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: mat-exam-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mat-exam
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - mat_exam:/var/lib/postgresql/data

volumes:
  mat_exam:
